### ISSUE TITLE
Release alpha

### ISSUE THREAD

**Issue by kvendrik** [kvendrik/intercom-react#5]

**Comment by oyeanuj** [comment]
Hi @kvendrik! This component looks great, so I was wondering how ready is it yet? I know you mentioned WIP but what could I expect to work or not work?

**Comment by kvendrik** [comment]
Hey @oyeanuj!

The only big thing that still needs to be fixed is [the build](https://github.com/kvendrik/intercom-react/issues/2). When thats fixed I would say the alpha release is pretty much good to go. I currently don't have time to finish this up and probably won't for a while but feel free to contribute. The commands in the [package](https://github.com/kvendrik/intercom-react/blob/master/package.json#L14) should be pretty straight forward and I'd love to answer any questions you may have.

**Comment by kvendrik** [comment]
This is pretty much ready to be released but before we do https://github.com/kvendrik/intercom-react/issues/4 should be checked as well as some of the other basic Intercom functionality.
